spring.application.name=ms-productos

# Puerto (diferente a MS-Auth que usa 8081)
server.port=8082

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/db_productos
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración para carga de archivos CSV
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Validación de proveedor (false hasta que MS-Proveedores esté listo)
validar.proveedor.activo=false
ms.proveedores.url=http://localhost:8083



